### ISSUE TITLE
Not working links in README.md

### ISSUE THREAD

**Issue by RIP21** [levibostian/dollabill-apple#5]
Thanks for the project :) Hasn't used it yet but I think I will.

You have 2 links not working in this section.
https://github.com/levibostian/dollabill-apple#documentation

1st and 3rd. Will be nice to get that fixed :)

**Comment by RIP21** [comment]
Also, unsure if beta release is good or 0.1.0 release is preferable? :)

**Comment by levibostian** [comment]
Welcome, @RIP21. Thanks for checking out the project! 

Links in the README fixed. 

I suggest using [the latest release](https://github.com/levibostian/dollabill-apple/releases) listed at the top of the page which at this time is `1.0.0-beta.2`.

**Comment by RIP21** [comment]
Good! Thanks. Any issues I'll encounter I'll let you know.

And, yeah 0.1.0 is just "hello world" :D
