### ISSUE TITLE
Error: Cannot find module 'types-apple-iap'

### ISSUE THREAD

**Issue by RIP21** [levibostian/dollabill-apple#6]
This is what you get if you don't install `types-apple-iap` :) 

Error: Cannot find module 'types-apple-iap'

**Comment by levibostian** [comment]
yes, that is expected. 

Do you have any suggestions based off of this?

**Comment by RIP21** [comment]
Just write some installation instruction with obvious yet useful sometimes npm install.... That will make this clear. Also haven't checked but put it into peerDependencies if you haven't already so tools will also warn the user of missing peer.

Also. Will be nice to get "stable" version on NPM as betas in pkg json trigger some people :)

**Comment by levibostian** [comment]
Great idea. Feel free to create a pull request with your ideas. If you need help, ask here and I'm happy to answer questions. 

As far as going to stable, I agree with you. I don't feel the module is stable quite yet as it's not running in production *anywhere*. Not even in any of my projects at this moment.
