### ISSUE TITLE
Cannot run check in sandbox mode

### ISSUE THREAD

**Issue by RIP21** [levibostian/dollabill-apple#7]
Hi.

I cannot see any public API, aside from calling `runVerifyReceipt` importing it this way 
```
import { runVerifyReceipt } from 'dollabill-apple/verify_receipt'
``` 
in order to run verify with a sandbox environment. I guess that shall be accessed.

**Comment by RIP21** [comment]
Ah. I guess it's intentional behavior :)

> Verify your receipt first with the production URL; proceed to verify with the sandbox URL if you receive a 21007 status code. Following this approach ensures that you do not have to switch between URLs while your application is tested, reviewed by App Review, or live in the App Store.

Closing it :)

**Comment by levibostian** [comment]
Ah, great find. Yes, this is the intended behavior based off of Apple's docs.

**Comment by RIP21** [comment]
Adding small hint in the jsdoc will be nice. As Apple docs are unstructured piece of shit so this info is really easy to miss :)

**Comment by levibostian** [comment]
Great idea. Feel free to create a pull request with your ideas. If you need help, ask here and I'm happy to answer questions.
